version: 1
formatters:
  simple:
    format: '{levelname} {name} {message}'
    style: '{'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: 'build/bxi.log'
    encoding: utf8
    mode: 'a'
loggers:
  eval-error:
    level: DEBUG
    handlers: [console,file]
  lenskit:
    level: INFO
    handlers: [console,file]
  simulation_utils:
    level: DEBUG
    handlers: [console,file]
  root:
    level: DEBUG
    handler: [console,file]
